---
_extends: .github

repository:
  name: js-bugz
  description: TokTok issue and pull request management bot
  topics: toktok, javascript, probot, github

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - DeepCode
          - "LGTM analysis: JavaScript"
          - Hound
          - Travis CI - Pull Request
          - code-review/reviewable
          - codecov/patch
          - codecov/project
