---
_extends: .github

repository:
  name: js-bugz
  description: TokTok issue and pull request management bot
  topics: toktok, javascript, probot, github
  has_issues: true

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - Travis CI - Pull Request
          - code-review/reviewable
          - codecov/patch
          - codecov/project
